
name = "valeofc357"
type = "webpack"
account_id = ""
zone_id = ""
route = ""
workers_dev = true

[site]
bucket = "dist"
entry-point = "src/_worker.js"

[build]
command = "npm install --legacy-peer-deps && npm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

[env.production]
NODE_VERSION = "18"

# SPA configuration
[[routes]]
pattern = "/*"
script = "src/_worker.js"
